<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'fullname'	=> 'Administrator',
                'username' => 'adminmusran',
                'password'	=> bcrypt('adminMus4b123!*'),
                'role' => 'Admin',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // cabang
            [
                'fullname'	=> 'PRMPCU1',
                'username' => 'PRMPCU1',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU2',
                'username' => 'PRMPCU2',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU3',
                'username' => 'PRMPCU3',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU4',
                'username' => 'PRMPCU4',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU5',
                'username' => 'PRMPCU5',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU6',
                'username' => 'PRMPCU6',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU7',
                'username' => 'PRMPCU7',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU8',
                'username' => 'PRMPCU8',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU9',
                'username' => 'PRMPCU9',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU10',
                'username' => 'PRMPCU10',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU11',
                'username' => 'PRMPCU11',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU12',
                'username' => 'PRMPCU12',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU13',
                'username' => 'PRMPCU13',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU14',
                'username' => 'PRMPCU14',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU15',
                'username' => 'PRMPCU15',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU16',
                'username' => 'PRMPCU16',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU17',
                'username' => 'PRMPCU17',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU18',
                'username' => 'PRMPCU18',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU19',
                'username' => 'PRMPCU19',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU20',
                'username' => 'PRMPCU20',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU21',
                'username' => 'PRMPCU21',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU22',
                'username' => 'PRMPCU22',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU23',
                'username' => 'PRMPCU23',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU24',
                'username' => 'PRMPCU24',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU25',
                'username' => 'PRMPCU25',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU26',
                'username' => 'PRMPCU26',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU27',
                'username' => 'PRMPCU27',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU28',
                'username' => 'PRMPCU28',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU29',
                'username' => 'PRMPCU29',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU30',
                'username' => 'PRMPCU30',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU31',
                'username' => 'PRMPCU31',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU32',
                'username' => 'PRMPCU32',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU33',
                'username' => 'PRMPCU33',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU34',
                'username' => 'PRMPCU34',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU35',
                'username' => 'PRMPCU35',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU36',
                'username' => 'PRMPCU36',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU37',
                'username' => 'PRMPCU37',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU38',
                'username' => 'PRMPCU38',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU39',
                'username' => 'PRMPCU39',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU40',
                'username' => 'PRMPCU40',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU41',
                'username' => 'PRMPCU41',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU42',
                'username' => 'PRMPCU42',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU43',
                'username' => 'PRMPCU43',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU44',
                'username' => 'PRMPCU44',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU45',
                'username' => 'PRMPCU45',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU46',
                'username' => 'PRMPCU46',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU47',
                'username' => 'PRMPCU47',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU48',
                'username' => 'PRMPCU48',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU49',
                'username' => 'PRMPCU49',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fullname'	=> 'PRMPCU50',
                'username' => 'PRMPCU50',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],           
            [
                'fullname'	=> 'PRMPCU51',
                'username' => 'PRMPCU51',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],           
            [
                'fullname'	=> 'PRMPCU52',
                'username' => 'PRMPCU52',
                'password'	=> bcrypt('MUSYRAN123'),
                'role' => 'User',
                'submited' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],           
    ]);
    }
}
